# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Data saving (Realm)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Data saving (Realm)
  
  pod 'RealmSwift'
  pod 'Alamofire'
    
end
